server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri.html $uri/ /index.html; }
    location /pdf/ { add_header Content-Disposition inline; }
    gzip on;
    gzip_types text/css application/javascript image/svg+xml application/json;
}
